name = input()
surname = input()
favorite_animal = input()
zodiac_sign = input()
print('Индивидуальный гороскоп для пользователя', name, surname)
print('Кем вы были в прошлой жизни:', favorite_animal)
print('Ваш знак зодиака -', zodiac_sign, ', поэтому вы - тонко чувствующая натура.')